# Chapter 9: Error Handling in C++

## C API Style Error Handling
    IN VIDEO: Basic Error Handling

### Types of Errors:

* Preconditions
* Postconditions
* Class invariants

### Error Handling on Win32 API

* Client executes API/member function call
* Library, DLL detects error and then calls SetLastError or SetLastErrorEx
* Client calls GetLastError
* Error code is mapped to system error code
* Use API to FormatMessage for formatted error message
* Included from <windows.h>



### Error Handling on Unix/Posix API

* Client executes API/member function call
* Library, or code sets global static errno variable
* Client checks errno and verifies not success (errno != 0)
* Client calls either perror or strerror for error message

Here is an example of error handling on Linux API using C style:

```c++
std::string fname = "/some/path/no_file_found.txt";
if ( open(fname.c_str(), 0_RDONLY, 
    S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH) == -1 ) {
        std::cerr << strerror(errno) << std::endl;
    }
```

## C++ API Style Error Handling

    IN VIDEO: Introduction to Exceptions

Here is an example of some C++ code without any error handling on Linux API using C++ style:

```c++
std::string fname = "/some/path/no_file_found.txt";
fs::FileReader<std::string> reader(name);
```

But there is no error handling yet, all that we have accomplished is:
* Moved from C API to C++ Class
* Encapsulated file reading behavior within a class
* Internal semantics of file reading opaque to clients
* Error detection responsibilty of FileReader (callee)
* Error Handling responsibilty of client (caller)

### Single Responsibility Principle

A class should have only one reason to change

### Law of Demeter

* A design principle
* "You can communicate directly with your friends, but not your friend's friends."
* Relates to any level of abstraction - functions, class, methods etc.
* Yo will often hear of "Law of Demeter Violations"

Here is an example of a Law of Demeter Violation:
```c++
std::string fname = "/some/path/no_file_found.txt";
fs::FileReader<std::string> reader(name);

if (reader.file.is_good()) {
    // The 'file' above is a Law of Demeter violation. This is becuse 'reader' 
    // is a friend of ours so we can query 'reader' directly, but 'file' is a 
    // friend of 'reader', so although 'reader' can query 'file' directly, we 
    // cannot query 'file'. Therefore cannot call method on 'reader.file'
}
```

### Exception

* Mechanism to decouple caller from point of error detection
* The callee signals the type of error using exception object
* Changes the execution path
* Caller can deal with exception or allow it to propagate
* Prevents future failure by preventing application from continuing
* An Exception is an ordinary class or struct

### STL Exceptions
    IN VIDEO: Introduction to STL Exceptions

* To make use of stl exceptions we need to include `#include<stdexcept>`
* If we want to create our own custom exceptions we should derive them from one of the STL exceptions, although we don't have to.
* Therefore if want Generic derivation we can use the following classes
    - `std::exception`
        + Can be used as an exception
        + Does not accept arguments
        + Not very useful without added data for communicating error and context of error
        + Acts as the base class for all, either directly or indirectly, STL exceptions
    - `std::logic_error`
    - `std::runtime_error`
* If we have specialized exceptions we can also specialized the base classes.

Here are the STL Exceptions
* Exceptions derived directly from `std::exception`

    | Exception | Description |
    | --------- | ----------- |
    | `bad_alloc` | An error thrown when a request to allocate memory fails |
    | `bad_cast` | An exception thrown when a dynamic cast fails |
    | `bad_exception` | An exception thrown when a bad exception handler is encountered | 
    | `bad_function_call` | An exception thrown when a bad function call is encountered |
    | `bad_typeid` | thrown when typeid called on nullptr |
    | `bad_weak_ptr` | thrown by std::shared_ptr when encountered expired weak_ptr |
    | `logic_error` | A logic_error exception |
    | `runtime_error` | A runtime_error exception |

* Exceptions derived directly from `std::logic_error`

    | Exception | Description |
    | --------- | ----------- |
    | domain_error | An error related to mathematical function or domain of some mathematical range |
    | future_error | An error related to a std::promise |
    | invalid_argument | An exception due to an invalid argument |
    | length_error | An exception due to a length error |
    | out_of_range | Value is out of range. For instance an array index |

* Exceptions derived directly from `std::runtime_error`

    | Exception | Description |
    | --------- | ----------- |
    | overflow_error | An error related to arithmetic overflows |
    | range_error | An error that can be used to report situation involving computations |
    | system_error | An exception thrown when the system (OS) encounters an error |
    | underflow_error | An exception that can be thrown for arithmethic underflow |

<!-- --> 

    IN VIDEO: Programming with Exceptions

* If we want to just propagate an exception to be handled later we don't do anything, although if we never handle the exception then eventually the program will terminate.
    ```c++
    std::string fname = "/some/path/no_file_found.txt";
    fs::FileReader<std::string> reader(name);
    ```

* When however we want to handle the exception we can use a try-catch block like below:
    ```c++
    try {
        std::string fname = "/some/path/no_file_found.txt";
        fs::FileReader<std::string> reader(name);
    } catch (const FileReaderException& e) { //using const is recommended
        std::cerr << "Error: " << e.what() << std::endl;
    }
    ```

* If we want to catch **all** exceptions, we can do the following:
    ```c++
    try {
        std::string fname = "/some/path/no_file_found.txt";
        fs::FileReader<std::string> reader(name);
    } catch (...) { //Use the '...' to catch all exceptions
        auto eptr = std::current_exception();
        try {
            std::rethrow_exception(eptr);
        } catch (const FileReaderException& e) { //using const is recommended
            std::cerr << "Error: " << e.what() << std::endl;
        }
    }
    ```
